import { useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Bars } from '../components/charts';
import { Icon } from '../components/Icon';
import { GenerateInvoiceModal, METHOD_ICON, RecordPaymentModal } from '../components/modals';
import { Badge, Btn, Card, CardHead, Delta, IconBtn, Kpi, MoreMenu, Num, PageHead, Pager, Person, Progress, SearchBox, Seg, SelectBox, Tabs, Empty } from '../components/ui';
import { MONTHS_12 } from '../data/history';
import type { Invoice, Member, Method } from '../data/types';
import { TODAY, addDays, fmtDate, fmtShort, fmtTime, weekday } from '../lib/date';
import { count, inr } from '../lib/format';
import { isCurrentMonth, isToday } from '../store/selectors';
import { useStore } from '../store/store';
import { useRevenueSeries } from './Dashboard';

const TABS = ['All', 'Paid', 'Pending', 'Overdue', 'Failed'] as const;
type Tab = (typeof TABS)[number];
const PER_PAGE = 10;

function downloadInvoice(inv: Invoice, m: Member | undefined) {
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${inv.id}</title><style>body{font-family:Arial,sans-serif;max-width:640px;margin:40px auto;color:#111}h1{margin:0}table{width:100%;border-collapse:collapse;margin-top:24px}td,th{padding:10px;border-bottom:1px solid #ddd;text-align:left}.r{text-align:right}</style></head><body>
<h1>CLUB29 GYM</h1><p>Tax invoice · ${inv.id}<br>Date: ${fmtDate(inv.date)}</p>
<p><b>Billed to</b><br>${m?.name ?? ''} (${inv.memberId})<br>${m?.phone ?? ''}<br>${m?.email ?? ''}</p>
<table><tr><th>Item</th><th class="r">Amount</th></tr><tr><td>${inv.item}</td><td class="r">${inr(inv.amount / 1.18)}</td></tr><tr><td>GST 18%</td><td class="r">${inr(inv.amount - inv.amount / 1.18)}</td></tr><tr><th>Total</th><th class="r">${inr(inv.amount)}</th></tr></table>
<p>Paid via ${inv.method ?? '—'} · Status: ${inv.status}</p><p style="color:#777">Demo invoice generated by the Club29 staff prototype.</p></body></html>`;
  const a = document.createElement('a');
  a.href = URL.createObjectURL(new Blob([html], { type: 'text/html' }));
  a.download = `${inv.id}.html`;
  a.click();
  URL.revokeObjectURL(a.href);
}

export default function Payments() {
  const { invoices, members, remind, retryInvoice, toast } = useStore();
  const nav = useNavigate();
  const [params] = useSearchParams();
  const [tab, setTab] = useState<Tab>((TABS as readonly string[]).includes(params.get('tab') ?? '') ? (params.get('tab') as Tab) : 'All');
  const [q, setQ] = useState(params.get('q') ?? '');
  const [month, setMonth] = useState(params.get('q') ? 'all' : 'sep');
  const [method, setMethod] = useState('all');
  const [range, setRange] = useState<'Week' | 'Month' | 'Year'>('Month');
  const [page, setPage] = useState(1);
  const [modal, setModal] = useState<'' | 'pay' | 'invoice'>('');
  const [payFor, setPayFor] = useState<Member | undefined>();
  const rev = useRevenueSeries();
  const byId = useMemo(() => new Map(members.map((m) => [m.id, m])), [members]);

  const paid = invoices.filter((i) => i.status === 'Paid');
  const today = paid.filter((i) => isToday(i.date));
  const pending = invoices.filter((i) => i.status === 'Pending');
  const overdue = invoices.filter((i) => i.status === 'Overdue');
  const month$ = paid.filter((i) => isCurrentMonth(i.date));
  const sum = (xs: Invoice[]) => xs.reduce((s, i) => s + i.amount, 0);
  const lastToday = today.sort((a, b) => b.date.getTime() - a.date.getTime())[0];

  const chart = range === 'Month' ? { values: rev.daily.map((v) => Math.round(v / 1000)), labels: rev.daily.map((_, i) => String(i + 1)), fmt: (v: number) => (v ? `₹${v}k` : '0'), tip: (l: string, v: number) => `${l} Sep: ₹${v}k`, sub: 'September 2026, in ₹ thousand' }
    : range === 'Week' ? { values: rev.daily.slice(-7).map((v) => Math.round(v / 1000)), labels: Array.from({ length: 7 }, (_, i) => (i === 6 ? 'Today' : weekday(addDays(TODAY, i - 6)))), fmt: (v: number) => (v ? `₹${v}k` : '0'), tip: (l: string, v: number) => `${l}: ₹${v}k`, sub: 'Last 7 days, in ₹ thousand' }
      : { values: rev.months, labels: MONTHS_12, fmt: (v: number) => (v ? `₹${v}L` : '0'), tip: (l: string, v: number) => `${l}: ₹${v} lakh`, sub: 'Last 12 months, in ₹ lakh' };
  const cmax = Math.ceil(Math.max(...chart.values) / 4 / 10) * 40 || 10;

  const methods: [Method, number][] = (['UPI', 'Card', 'Cash', 'Online'] as Method[]).map((m) => [m, sum(month$.filter((i) => i.method === m))]);
  const mTotal = methods.reduce((s, [, v]) => s + v, 0) || 1;

  const filtered = useMemo(() => {
    const s = q.trim().toLowerCase();
    return invoices.filter((i) => {
      if (tab !== 'All' && i.status !== tab) return false;
      if (month === 'sep' && !(i.date.getMonth() === 8 && i.date.getFullYear() === 2026) && i.status === 'Paid') return false;
      if (month === 'aug' && !(i.date.getMonth() === 7 && i.date.getFullYear() === 2026)) return false;
      if (method !== 'all' && i.method !== method) return false;
      if (s) { const m = byId.get(i.memberId); if (!(i.id.toLowerCase().includes(s) || m?.name.toLowerCase().includes(s) || i.memberId.toLowerCase().includes(s))) return false; }
      return true;
    }).sort((a, b) => b.date.getTime() - a.date.getTime());
  }, [invoices, tab, month, method, q, byId]);
  const counts = Object.fromEntries(TABS.map((t) => [t, t === 'All' ? invoices.length : invoices.filter((i) => i.status === t).length])) as Record<Tab, number>;
  const pages = Math.max(1, Math.ceil(filtered.length / PER_PAGE));
  const cur = Math.min(page, pages);
  const shown = filtered.slice((cur - 1) * PER_PAGE, cur * PER_PAGE);
  const openIds = [...new Set([...pending, ...overdue].map((i) => i.memberId))];

  return (
    <>
      <PageHead title="Payments & billing" sub="Collections, invoices and dues" right={<>
        <Btn icon="send" onClick={() => remind(openIds)}>Send reminder</Btn>
        <Btn icon="receipt" onClick={() => setModal('invoice')}>Generate invoice</Btn>
        <Btn v="primary" icon="plus" onClick={() => { setPayFor(undefined); setModal('pay'); }}>Record payment</Btn>
      </>} />
      <div className="grid g4">
        <Kpi label="Today’s collection" value={inr(sum(today))} meta={`${today.length} payments${lastToday ? ` · last at ${fmtTime(lastToday.date)}` : ''}`} icon="wallet" onClick={() => { setTab('Paid'); setQ(''); }} />
        <Kpi label="This month" value={inr(sum(month$))} meta={<><Delta>{((rev.sep / rev.aug - 1) * 100).toFixed(1)}%</Delta> vs August</>} icon="trend" />
        <Kpi label="Pending" value={inr(sum(pending))} meta={<><span style={{ color: 'var(--warn)', fontWeight: 700 }}>{pending.length} invoices</span> · links sent</>} icon="clock" onClick={() => setTab('Pending')} />
        <Kpi label="Overdue" value={inr(sum(overdue))} meta={<><span style={{ color: 'var(--bad)', fontWeight: 700 }}>{new Set(overdue.map((i) => i.memberId)).size} members</span> · past expiry</>} icon="receipt" onClick={() => setTab('Overdue')} />
      </div>
      <div className="grid g3">
        <Card className="span2">
          <CardHead title="Daily collections" sub={chart.sub} right={<Seg items={['Week', 'Month', 'Year'] as const} value={range} onChange={setRange} />} />
          <Bars h={240} values={chart.values} labels={chart.labels} max={cmax} ticks={[0, cmax / 4, cmax / 2, (cmax * 3) / 4, cmax]} fmt={chart.fmt} tip={chart.tip} hi={[chart.values.length - 1]} bw={range === 'Month' ? 16 : 30} />
        </Card>
        <Card>
          <CardHead title="Payment methods" sub="This month" />
          <div className="col" style={{ gap: 18 }}>
            {methods.map(([m, v]) => (
              <div key={m} className="col" style={{ gap: 8 }}>
                <div className="row" style={{ gap: 10, fontSize: 14 }}>
                  <span style={{ width: 30, height: 30, borderRadius: 8, background: 'var(--card2)', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', color: 'var(--tx2)' }}><Icon name={METHOD_ICON[m]} size={15} /></span>
                  <span className="grow" style={{ fontWeight: 700 }}>{m}</span>
                  <span className="num" style={{ color: 'var(--tx2)' }}>{inr(v)}</span>
                  <span className="num" style={{ width: 40, textAlign: 'right', fontWeight: 700 }}>{Math.round((v / mTotal) * 100)}%</span>
                </div>
                <Progress h={5} value={(v / mTotal) * 100} />
              </div>
            ))}
          </div>
          <div style={{ fontSize: 12, color: 'var(--tx3)', lineHeight: 1.5 }}>UPI and payment links settle to the Club29 account the next working day.</div>
        </Card>
      </div>

      <section className="table-card">
        <div className="tc-head col" style={{ gap: 16 }}>
          <div className="row between" style={{ gap: 16, flexWrap: 'wrap' }}>
            <CardHead title="Transactions" sub="All invoices and receipts" />
            <div className="row" style={{ gap: 8 }}>
              <SearchBox id="inv-search" value={q} onChange={(v) => { setQ(v); setPage(1); }} placeholder="Search invoice or member" width={260} />
              <SelectBox label="Month" value={month} onChange={(v) => { setMonth(v); setPage(1); }} width={170} options={[['sep', 'September 2026'], ['aug', 'August 2026'], ['all', 'All time']]} />
              <SelectBox label="Method" value={method} onChange={(v) => { setMethod(v); setPage(1); }} width={140} options={[['all', 'All methods'], ['UPI', 'UPI'], ['Card', 'Card'], ['Cash', 'Cash'], ['Online', 'Online']]} />
            </div>
          </div>
          <Tabs items={TABS} value={tab} onChange={(t) => { setTab(t); setPage(1); }} labels={{ Pending: `Pending · ${counts.Pending}`, Overdue: `Overdue · ${counts.Overdue}`, Failed: `Failed · ${counts.Failed}` }} />
        </div>
        <div className="table-scroll">
          <table className="tbl">
            <thead><tr><th>Member</th><th>Invoice</th><th>Plan</th><th className="r">Amount</th><th>Method</th><th>Date</th><th>Status</th><th className="r" /></tr></thead>
            <tbody>
              {shown.map((i) => {
                const m = byId.get(i.memberId);
                return (
                  <tr key={i.id}>
                    <td><Person name={m?.name ?? i.memberId} size={32} onClick={() => nav(`/members/${i.memberId}`)} /></td>
                    <td><span className="num" style={{ color: 'var(--tx)' }}>{i.id}</span></td>
                    <td>{i.item}</td>
                    <td className="r"><Num>{inr(i.amount)}</Num></td>
                    <td>{i.method ? <span className="row" style={{ gap: 8 }}><Icon name={METHOD_ICON[i.method]} size={15} color="var(--tx3)" />{i.method}</span> : <span className="muted">—</span>}</td>
                    <td>{i.status === 'Paid' || i.status === 'Failed' ? `${fmtShort(i.date)} · ${fmtTime(i.date)}` : i.status === 'Overdue' ? `Due ${fmtShort(i.date)}` : `${fmtShort(i.date)} · link sent`}</td>
                    <td><Badge kind={i.status === 'Paid' ? 'ok' : i.status === 'Pending' ? 'warn' : 'bad'}>{i.status}</Badge></td>
                    <td className="r">
                      {i.status === 'Paid' ? (
                        <div className="row" style={{ gap: 6, justifyContent: 'flex-end' }}>
                          <IconBtn sm icon="download" label={`Download ${i.id}`} onClick={() => { downloadInvoice(i, m); toast(`${i.id} downloaded`); }} />
                          <IconBtn sm icon="send" label={`Send ${i.id} on WhatsApp`} onClick={() => toast(`${i.id} sent to ${m?.name} on WhatsApp`, 'info')} />
                        </div>
                      ) : i.status === 'Failed' ? <Btn size="sm" icon="refresh" onClick={() => retryInvoice(i.id)}>Retry</Btn> : (
                        <div className="row" style={{ gap: 6, justifyContent: 'flex-end' }}>
                          <Btn size="sm" icon="send" onClick={() => remind([i.memberId])}>Remind</Btn>
                          <MoreMenu label={`More for ${i.id}`} items={[{ label: 'Mark as paid', icon: 'check', onClick: () => { setPayFor(m); setModal('pay'); } }, { label: 'Open member', icon: 'user', onClick: () => nav(`/members/${i.memberId}`) }]} />
                        </div>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          {!shown.length && <Empty>No transactions match these filters.</Empty>}
        </div>
        <div className="tc-foot">
          <span>Showing <span style={{ color: 'var(--tx)', fontWeight: 700 }}>{shown.length}</span> of {count(filtered.length)} transactions</span>
          <Pager page={cur} pages={pages} onPage={setPage} />
        </div>
      </section>
      {modal === 'pay' && <RecordPaymentModal member={payFor} onClose={() => setModal('')} />}
      {modal === 'invoice' && <GenerateInvoiceModal onClose={() => setModal('')} />}
    </>
  );
}
